module.exports = {
  Answer: require('./Answer'),
  Base: require('./Base'),
  Bind: require('./Bind'),
  Conference: require('./Conference'),
  Dial: require('./Dial'),
  Echo: require('./Echo'),
  Hangup: require('./Hangup'),
  Intercept: require('./Intercept'),
  Number: require('./Number'),
  Playback: require('./Playback'),
  Record: require('./Record'),
  Ringback: require('./Ringback'),
  SipAccount: require('./SipAccount'),
  SipUri: require('./SipUri'),
  Speak: require('./Speak'),
  Wait: require('./Wait'),
  Work: require('./Work'),
};
